apiVersion: v2
name: metagrid
description: A Helm chart for the Metagrid frontend/backend
type: application
version: 0.1.7
appVersion: "1.2.1"
home: https://github.com/esgf2-us/metagrid-k8s
sources:
  - https://github.com/aims-group/metagrid
dependencies:
- name: postgresql-ha
  alias: postgresql
  condition: postgresql.enabled
  version: ">=9.2.0"
  repository: "https://charts.bitnami.com/bitnami"
maintainers:
  - name: Jason Boutte
    email: boutte3@llnl.gov

