apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metagrid.fullname" . }}-react
  labels:
    {{- include "metagrid.labels" . | nindent 4 }}
    app.kubernetes.io/component: react
data:
  RELEASE: production
  PUBLIC_URL: {{ .Values.react.urlPath }}
  REACT_APP_PREVIOUS_URL: {{ default "" .Values.react.previousUrlPath }}
  REACT_APP_METAGRID_API_URL: {{ include "metagrid.django.url" . }}
  REACT_APP_AUTHENTICATION_METHOD: {{ .Values.authType }}
  {{- if eq .Values.authType "globus" }}
  REACT_APP_GLOBUS_REDIRECT: {{ .Values.globus.frontend.redirect }}
  REACT_APP_CLIENT_ID: {{ .Values.globus.frontend.clientID }}
  REACT_APP_GLOBUS_NODES: {{ .Values.globus.frontend.nodes | join "," | quote }}
  {{- end }}
  REACT_APP_WGET_API_URL: {{ .Values.wgetApiUrl }}
  REACT_APP_SEARCH_URL: {{ .Values.searchUrl }}
  REACT_APP_ESGF_NODE_STATUS_URL: {{ .Values.esgfNodeStatusUrl }}
  {{- with .Values.keyCloak }}
  REACT_APP_KEYCLOAK_REALM: {{ .realm }}
  REACT_APP_KEYCLOAK_URL: {{ .url }}
  REACT_APP_KEYCLOAK_CLIENT_ID: {{ .clientID }}
  {{- end }}
  REACT_APP_DJANGO_LOGIN_URL: {{ include "metagrid.django.loginUrl" . }}
  REACT_APP_DJANGO_LOGOUT_URL: {{ include "metagrid.django.logoutUrl" . }}
  {{- with .Values.react.hotjar }}
  REACT_APP_HOTJAR_ID: {{ .id | quote }}
  REACT_APP_HOTJAR_SV: {{ .sv | quote }}
  {{- end }}
  REACT_APP_GOOGLE_ANALYTICS_TRACKING_ID: {{ default "" .Values.react.googleAnalyticsID }}
  # TODO default metagrid nginx adds location for PREVIOUS_URL and breaks reverse proxy
  default.conf: |
    server {
      listen {{ .Values.react.service.port }};

      location / {
        return 301 /metagrid;
      }

      location ^~ {{ printf "/%s" (trimPrefix "/" .Values.react.urlPath) }} {
        alias   /usr/share/nginx/html/;
        index  index.html index.htm;
        try_files $uri $uri/ {{ printf "/%s" (trimPrefix "/" .Values.react.urlPath) }}/index.html;
      }

      error_page   500 502 503 504  /50x.html;

      location = /50x.html {
        root   /usr/share/nginx/html;
      }
    }
