apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metagrid.fullname" . }}-react
  labels:
    {{- include "metagrid.labels" . | nindent 4 }}
    app.kubernetes.io/component: react
    {{- with .Values.react.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/react/configmap.yaml") . | sha256sum }}
    {{- with .Values.react.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.react.autoscaling.enabled }}
  replicas: {{ .Values.react.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "metagrid.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: react
  template:
    metadata:
      {{- with .Values.react.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "metagrid.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: react
    spec:
      {{- $react := deepCopy .Values.react }}
      {{- $_ := set $react "name" "react" }}
      {{- $_ := set $react.image "pullSecrets" .Values.imagePullSecrets }}
      {{- $_ := set $react "env" (mustMerge (default dict $react.env) (dict "SKIP_NGINX_CONF" "true" "DEBUG" "true" "PUBLIC_URL" .Values.react.urlPath)) }}
      {{- $config := dict "configMapRef" (dict "name" (printf "%s-react" (include "metagrid.fullname" .))) }}
      {{- $_ := set $react "envFrom" (list $config) }}
      {{- $_ := set $react "TemplateValues" . }}
      {{- $_ := set $react.service "name" "http" }}
      {{- $_ := set $react "livenessProbe" (dict "httpGet" (dict "port" "http" "path" .Values.react.urlPath)) }}
      {{- $_ := set $react "readinessProbe" (dict "httpGet" (dict "port" "http" "path" .Values.react.urlPath)) }}
      {{- $resourceName := printf "%s-react" (include "metagrid.fullname" .) }}
      {{- $persistence := dict "type" "configmap" "name" "nginx-conf" "resourceName" $resourceName "mountPath" "/etc/nginx/conf.d/default.conf" "subPath" "default.conf" "readOnly" true }}
      {{- $_ := set $react "persistence" $persistence }}
      {{- include "metagrid.podSpec" $react | nindent 6 }}
