apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metagrid.fullname" . }}-django
  labels:
    {{- include "metagrid.labels" . | nindent 4 }}
    app.kubernetes.io/component: django
data:
  PYTHONBUFFERED: "1"
  {{- with .Values.django.gunicornCmdArgs }}
  GUNICORN_CMD_ARGS: {{ . | quote }}
  {{- end }}
  DOMAIN_NAME: {{ default "127.0.0.1" .Values.ingress.django.host }}
  DOMAIN_SUBDIRECTORY: {{ trimPrefix "/" .Values.django.urlPath }}
  DJANGO_DEBUG: {{ .Values.django.debug | quote }}
  DJANGO_SETTINGS_MODULE: config.settings.production
  DJANGO_SECRET_KEY: {{ default (randAlphaNum 32) .Values.django.secretKey }}
  DJANGO_ADMIN_URL: {{ .Values.django.adminUrl }}
  DJANGO_ALLOWED_HOSTS: {{ include "metagrid.djangoAllowedHosts" . | quote }}
  DJANGO_SECURE_SSL_REDIRECT: "False"
  CORS_ALLOWED_ORIGINS: {{ include "metagrid.django.corsOriginWhitelist" . }}
  # CORS_ORIGIN_WHITELIST: {{ include "metagrid.django.corsOriginWhitelist" . }}
  KEYCLOAK_URL: {{ .Values.keyCloak.url }}
  KEYCLOAK_REALM: {{ .Values.keyCloak.realm }}
  KEYCLOAK_CLIENT_ID: {{ .Values.keyCloak.clientID }}
  DJANGO_LOGIN_REDIRECT_URL: {{ include "metagrid.django.loginRedirect" . | quote }}
  DJANGO_LOGOUT_REDIRECT_URL: {{ include "metagrid.django.logoutRedirect" . | quote }}
  GLOBUS_CLIENT_KEY: {{ .Values.globus.backend.clientID }}
  GLOBUS_CLIENT_SECRET: {{ .Values.globus.backend.clientSecret }}
  # REACT_APP_WGET_API_URL: {{ .Values.wgetApiUrl }}
  # REACT_APP_SEARCH_URL: {{ .Values.searchUrl }}
  # REACT_APP_ESGF_NODE_STATUS_URL: {{ .Values.esgfNodeStatusUrl }}
  # REACT_APP_ESGF_SOLR_URL: {{ .Values.solrUrl }}
  POSTGRES_HOST: {{ include "metagrid.pg_host" . }}
  POSTGRES_PORT: {{ include "metagrid.pg_port" . | quote }}
