apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metagrid.fullname" . }}-django
  labels:
    {{- include "metagrid.labels" . | nindent 4 }}
    app.kubernetes.io/component: django
    {{- with .Values.django.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- $configmap := include (print $.Template.BasePath "/django/configmap.yaml") . }}
    {{- $secret := include (print $.Template.BasePath "/django/secret.yaml") . }}
    checksum/config: {{ print $configmap $secret | sha256sum }}
    {{- with .Values.django.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.django.autoscaling.enabled }}
  replicas: {{ .Values.django.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "metagrid.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: django
  template:
    metadata:
      {{- with .Values.django.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "metagrid.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: django
    spec:
      {{- $django := deepCopy .Values.django }}
      {{- $_ := set $django "name" "django" }}
      {{- $_ := set $django.image "pullSecrets" .Values.imagePullSecrets }}
      {{- $_ := set $django "args" (list "/start") }}
      {{- $config := dict "configMapRef" (dict "name" (printf "%s-django" (include "metagrid.fullname" .))) }}
      {{- $secret := dict "secretRef" (dict "name" (printf "%s-django" (include "metagrid.fullname" .))) }}
      {{- $_ := set $django "envFrom" (list $config $secret) }}
      {{- $_ := set $django "TemplateValues" . }}
      {{- $_ := set $django.service "name" "http" }}
      {{- $_ := set $django "livenessProbe" (dict "tcpSocket" (dict "port" "http")) }}
      {{- $_ := set $django "readinessProbe" (dict "tcpSocket" (dict "port" "http")) }}
      {{- include "metagrid.podSpec" $django | nindent 6 }}
